// Device types
export type DeviceType =
  | 'server' | 'switch' | 'router' | 'firewall' | 'storage'
  | 'pdu' | 'patch_panel' | 'kvm' | 'load_balancer'
  | 'cable_manager' | 'blade_chassis' | 'blade' | 'other';

// Sections
export interface DeviceFormSections {
  showRackPlacement: boolean;       // rack_id, rack_unit_start, rack_unit_size, face
  showPowerPhysical: boolean;       // power_rated_w, weight_kg
  showLifecycleDates: boolean;      // purchase_date, warranty_expiry, end_of_support_date, end_of_life_date
  showManagementIp: boolean;        // management_ip, management_protocol
  showSnmp: boolean;                // snmp_community, snmp_version
  showSsh: boolean;                 // ssh_username, ssh_password
  showServerExtension: boolean;     // form_factor, cpu/ram/storage fields
  showBladeExtension: boolean;      // blade_chassis_id, blade_slot (blade type only)
  showNetworkExtension: boolean;    // port_count, os_type, spanning_tree, etc.
  showSpanningTree: boolean;        // spanning_tree_mode/priority (switch only)
  showStacking: boolean;            // stacking_enabled, stack_member_id (switch only)
  showPduExtension: boolean;        // outlet_count, outlet_type, etc.
  rackPlacementRequired: boolean;   // whether rack_unit_start is required
}

export const DEVICE_FORM_CONFIG: Record<DeviceType, DeviceFormSections> = {
  server: {
    showRackPlacement: true,
    showPowerPhysical: true,
    showLifecycleDates: true,
    showManagementIp: true,
    showSnmp: false,
    showSsh: true,
    showServerExtension: true,
    showBladeExtension: false,
    showNetworkExtension: false,
    showSpanningTree: false,
    showStacking: false,
    showPduExtension: false,
    rackPlacementRequired: true,
  },
  blade_chassis: {
    showRackPlacement: true,
    showPowerPhysical: true,
    showLifecycleDates: true,
    showManagementIp: true,
    showSnmp: false,
    showSsh: true,
    showServerExtension: true,
    showBladeExtension: false,
    showNetworkExtension: false,
    showSpanningTree: false,
    showStacking: false,
    showPduExtension: false,
    rackPlacementRequired: true,
  },
  blade: {
    showRackPlacement: false,
    showPowerPhysical: false,
    showLifecycleDates: false,
    showManagementIp: true,
    showSnmp: false,
    showSsh: true,
    showServerExtension: true,
    showBladeExtension: true,
    showNetworkExtension: false,
    showSpanningTree: false,
    showStacking: false,
    showPduExtension: false,
    rackPlacementRequired: false,
  },
  switch: {
    showRackPlacement: true,
    showPowerPhysical: true,
    showLifecycleDates: true,
    showManagementIp: true,
    showSnmp: true,
    showSsh: true,
    showServerExtension: false,
    showBladeExtension: false,
    showNetworkExtension: true,
    showSpanningTree: true,
    showStacking: true,
    showPduExtension: false,
    rackPlacementRequired: true,
  },
  router: {
    showRackPlacement: true,
    showPowerPhysical: true,
    showLifecycleDates: true,
    showManagementIp: true,
    showSnmp: true,
    showSsh: true,
    showServerExtension: false,
    showBladeExtension: false,
    showNetworkExtension: true,
    showSpanningTree: false,
    showStacking: false,
    showPduExtension: false,
    rackPlacementRequired: true,
  },
  firewall: {
    showRackPlacement: true,
    showPowerPhysical: true,
    showLifecycleDates: true,
    showManagementIp: true,
    showSnmp: true,
    showSsh: true,
    showServerExtension: false,
    showBladeExtension: false,
    showNetworkExtension: true,
    showSpanningTree: false,
    showStacking: false,
    showPduExtension: false,
    rackPlacementRequired: true,
  },
  load_balancer: {
    showRackPlacement: true,
    showPowerPhysical: true,
    showLifecycleDates: true,
    showManagementIp: true,
    showSnmp: true,
    showSsh: true,
    showServerExtension: false,
    showBladeExtension: false,
    showNetworkExtension: true,
    showSpanningTree: false,
    showStacking: false,
    showPduExtension: false,
    rackPlacementRequired: true,
  },
  pdu: {
    showRackPlacement: true,
    showPowerPhysical: true,
    showLifecycleDates: true,
    showManagementIp: true,
    showSnmp: true,
    showSsh: false,
    showServerExtension: false,
    showBladeExtension: false,
    showNetworkExtension: false,
    showSpanningTree: false,
    showStacking: false,
    showPduExtension: true,
    rackPlacementRequired: true,
  },
  storage: {
    showRackPlacement: true,
    showPowerPhysical: true,
    showLifecycleDates: true,
    showManagementIp: true,
    showSnmp: true,
    showSsh: true,
    showServerExtension: false,
    showBladeExtension: false,
    showNetworkExtension: false,
    showSpanningTree: false,
    showStacking: false,
    showPduExtension: false,
    rackPlacementRequired: true,
  },
  kvm: {
    showRackPlacement: true,
    showPowerPhysical: true,
    showLifecycleDates: true,
    showManagementIp: true,
    showSnmp: false,
    showSsh: true,
    showServerExtension: false,
    showBladeExtension: false,
    showNetworkExtension: false,
    showSpanningTree: false,
    showStacking: false,
    showPduExtension: false,
    rackPlacementRequired: true,
  },
  patch_panel: {
    showRackPlacement: true,
    showPowerPhysical: false,
    showLifecycleDates: false,
    showManagementIp: false,
    showSnmp: false,
    showSsh: false,
    showServerExtension: false,
    showBladeExtension: false,
    showNetworkExtension: false,
    showSpanningTree: false,
    showStacking: false,
    showPduExtension: false,
    rackPlacementRequired: true,
  },
  cable_manager: {
    showRackPlacement: true,
    showPowerPhysical: false,
    showLifecycleDates: false,
    showManagementIp: false,
    showSnmp: false,
    showSsh: false,
    showServerExtension: false,
    showBladeExtension: false,
    showNetworkExtension: false,
    showSpanningTree: false,
    showStacking: false,
    showPduExtension: false,
    rackPlacementRequired: true,
  },
  other: {
    showRackPlacement: true,
    showPowerPhysical: true,
    showLifecycleDates: true,
    showManagementIp: true,
    showSnmp: true,
    showSsh: true,
    showServerExtension: false,
    showBladeExtension: false,
    showNetworkExtension: false,
    showSpanningTree: false,
    showStacking: false,
    showPduExtension: false,
    rackPlacementRequired: true,
  },
};

export function getDeviceFormConfig(deviceType: string): DeviceFormSections {
  return DEVICE_FORM_CONFIG[deviceType as DeviceType] ?? DEVICE_FORM_CONFIG.other;
}
